config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :animes do
    resources :reviews
  end
  root "animes#index"
end

app/models/anime.rb
class Anime < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :review

  has_attached_file :anime_img, styles: { :anime_index => "250x350", :anime_show => "325x475 "}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :anime_img, content_type: /\Aimage\/.*\z/
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :anime
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :anime
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :anime
  has_many :review
  # has_many :category
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :find_anime, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    if params[:category].blank?
      @animes = Anime.all.order("created_at DESC");
    else
      @category_id = Category.find_by(name: params[:category]).id
      @animes = Anime.where(:category_id => @category_id).order("created_at DESC")
    end
  end

  def show
    if @anime.review.blank?
      @average_review = 0
    else
      @average_review = @anime.review.average(:rating).round(2)
    end
  end

  def new
    @anime = current_user.anime.build
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def create
    @anime = current_user.anime.build(anime_params)
    @anime.category_id  = params[:category_id]

    if @anime.save
      redirect_to root_path
    else
      render "new"
    end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def update
    @anime.category_id  = params[:category_id]

    if @anime.update(anime_params)
      redirect_to anime_path(@anime)
    else
      render "edit"
    end
  end

  def destroy
    @anime.destroy
    redirect_to root_path
  end

  private
  def anime_params
    params.require(:anime).permit(:title, :description, :creator, :category_id, :anime_img)
  end

  def find_anime
    @anime = Anime.find(params[:id]);
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_anime
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
  end

  def create
    @review = Review.new(review_params)
    @review.anime_id = @anime.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to anime_path(@anime)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to anime_path(@anime)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to anime_path(@anime)
  end

  private

  def find_anime
    @anime = Anime.find(params[:anime_id])
  end

  def find_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/animes/_form.html.erb
<%= simple_form_for @anime do |f|%>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select Category") %>
  <%= f.file_field :anime_img %>
  <%= f.input :title, label: "Animation title" %>
  <%= f.input :description %>
  <%= f.input :creator %>
  <%= f.button :submit %>
<% end %>

app/views/animes/edit.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="new-play-form">
    <h1>Edit Anime</h1>

    <%= simple_form_for @anime, html: {multipart: true} do |f|%>
      <%= f.select :category_id, @categories %>
      <%= f.file_field :anime_img %>
      <%= f.input :title, label: "Animation title" %>
      <%= f.input :description %>
      <%= f.input :creator %>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/animes/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @animes.count == 0 %>
  <h3>There are no Animes in this Category</h3>
<% else %>
  <div class="row">
    <% @animes.each do |anime| %>
      <div class="col-md-3">
        <a href="/animes/<%= anime.id %>">
          <%= image_tag anime.anime_img.url(:anime_index), class: 'play' %>
        </a>
      </div>
<!--       <h2><%= link_to anime.title, anime_path(anime) %></h2> -->
    <% end %>
  </div>
<% end %>

app/views/animes/new.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="new-play-form">
    <h1>Add new Anime</h1>

    <%= render "form" %>
  </div>
</div>

app/views/animes/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag @anime.anime_img.url(:anime_show), class: "play-show" %>
  </div>
  <div class="col-md-8">
    <div class="play-info">
      <h2 class="play-title"><%= @anime.title %></h2>
      <h3 class="play-director"><span>By </span><%= @anime.creator %></h3>
      <h4 class="play-director"><%= @anime.category.name %></h4>
      <h4 class="avg-rating">Average Rating</h4>
      <div class="average-review-rating" data-score=<%= @average_review %>></div>
      <span class="number-of-reviews">From: <%= @anime.review.count %> reviews </span>
      <p class="play-desc"><%= @anime.description %></p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="reviews">
      <h1> Reviews </h1>
        <%= render @anime.review %>
        <%= link_to "Add Reviews", new_anime_review_path(@anime), class: 'btn-custom' %>
    </div>
  </div>
</div>

<div class="links btn-group">
  <% if user_signed_in? %>
    <% if @anime.user_id == current_user.id %>
      <%= link_to "Edit", edit_anime_path(@anime), class: "btn btn-custom" %>
      <%= link_to "Delete", anime_path(@anime), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-custom"%>
    <% end %>
  <% end %>
</div>

<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function(){
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function(){
      return $(this).attr('data-score')
    }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Animationrate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "AnimationRate", root_path, class: "navbar-brand" %>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <% if  user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Genres<span class="caret"></span></a>

          <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.name %>">
                <%= link_to category.name, animes_path(category: category.name), class: "link" %>
              </li>
            <% end %>
          </ul>
        </li>

        <% if  user_signed_in? %>
          <li><%= link_to "Add Anime", new_anime_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@anime, @anime.review.build]) do |f| %>
  <div id="rating-form">
    <label> Rating </label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit, :class => "btn-custom2" %>
<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div class="review">
  <div class="review-rating" data-score='<%= review.rating %>'></div>
  <p class="review-comment"><%= review.comment %></p>
  <% if user_signed_in? %>
    <% if review.user_id == current_user.id %>
      <div class="links btn-group">
        <%= link_to "Edit", edit_anime_review_path(review.anime, review), class: 'btn btn-custom' %>
        <%= link_to "Delete", anime_review_path(review.anime, review), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-custom' %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="edit-review-form">
    <h1>Edit Review</h1>
    <%= simple_form_for([@anime, @review]) do |f| %>
      <div id="rating-form">
        <label> Rating </label>
      </div>
      <%= f.input :comment %>
      <%= f.button :submit, :class => "btn-custom2" %>
    <% end %>
  </div>
</div>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="new-review-form">
    <h1>Post Review</h1>
    <%= render 'form' %>
  </div>
</div>